name: injectable_generator
description: Injectable is a convenient code generator for get_it. Inspired by Angular DI, Guice DI and inject.dart.
version: 2.7.0
homepage: https://github.com/Milad-Akarie/injectable

environment:
  sdk: ">=3.0.0<4.0.0"

dependencies:
  build: ^2.4.2
  source_gen: ^2.0.0
  path: ^1.9.0
  glob: ^2.1.2
  analyzer: ">=6.4.1 <8.0.0"
  code_builder: ^4.10.1
  dart_style: ^3.0.1
  injectable: ^2.5.0
#      path: ../injectable
  collection: ^1.17.1
  recase: ^4.1.0
  meta: ^1.12.0
dev_dependencies:
  build_runner: ^2.4.11
  build_test: ^2.2.3
  test: ^1.25.14
  lints: ^5.1.1
